### ISSUE TITLE
generate-syminks should purge the /Assets/ folder before trying to create new links

### ISSUE THREAD

**Issue by AnnoyingTechnology** [polyfony-inc/console#15]

**Comment by Jijac** [comment]
Remove previous links before generate new links.
Idem for Css and Js Caches.

	private static function generateSymlinksCommand() {
		// pretty introduction
		Console\Format::block('Generating assets symlinks', 'cyan', null, ['bold']);
		// define the bundles dir
		$bundles_dir = realpath(__DIR__.'/../../../../../Bundles/').'/';
		// for each bundle
		foreach(scandir($bundles_dir) as $bundle_name) {
			// bundle assets folder
			$bundles_assets_dir = $bundles_dir . $bundle_name .'/Assets/';
			// if the is no assets folder in that bundle
			if(!is_dir($bundles_assets_dir) || in_array($bundle_name,['.','..'])) {
				continue;
			} 
			Console\Format::line('Bundles/'.$bundle_name, 'white', null, ['bold']);
			// get assets for that bundle
			foreach(scandir($bundles_assets_dir) as $assets_type) {
				// the directory for theses assets in this bundle
				$bundle_assets_type_dir = $bundles_assets_dir . $assets_type . '/';
				// skip non valid directories
				if(!is_dir($bundle_assets_type_dir) || in_array($assets_type,['.','..','.DS_Store'])) {
					continue;
				}
				// set the root path
				$assets_root_path = realpath(__DIR__."/../../../../../../Public/Assets")."/{$assets_type}/";
				// if it doesn't already exist 
				if(!is_dir($assets_root_path)) {
					// create the path
					if(@mkdir($assets_root_path, 0777, true)) {
						// feedback
						Console\Format::line('  + Public/Assets/'.$assets_type.'/', 'green');
					}
					else {
						// feedback
						Console\Format::line('  X Public/Assets/'.$assets_type.'/ (failed)', 'red');
					}
				}
				// set the symlink 
				$assets_symbolic_path = $assets_root_path . $bundle_name;

				// if the symlink already exists remove it
				if(is_link($assets_symbolic_path)) {
					Console\Format::line('- removing : Public/Assets/'.$assets_type.'/'.$bundle_name.'/', 'gray');
					@unlink($assets_symbolic_path);
				
				}
				// create the symlink
				if(@symlink($bundle_assets_type_dir, $assets_root_path.$bundle_name)) {
					// feedback
					Console\Format::line('  + Public/Assets/'.$assets_type.'/'.$bundle_name.'/', 'green');
				}
				else {
					// feedback
					Console\Format::line('  X Public/Assets/'.$assets_type.'/'.$bundle_name.'/ (failed)', 'red');
				}
			}
		}
		
		// Generate Caches links
		// pretty introduction
		Console\Format::block('Generating assets caches symlinks', 'cyan', null, ['bold']);
		// define the caches dir
		$caches_dir = realpath(__DIR__.'/../../../../../Storage/Cache/Assets/').'/';
		// for each Assets cache
		foreach(scandir($caches_dir) as $cache_name) {
			// bundle assets folder
			$cache_assets_dir = $caches_dir . $cache_name .'/';
			// if the is no cache folder 
			if(!is_dir($cache_assets_dir) || in_array($cache_name,['.','..','.DS_Store'])) {
				continue;
			} 
			// set the root path
			$assets_root_path = realpath(__DIR__."/../../../../../../Public/Assets")."/{$cache_name}/";
			// set the symlink 
			$assets_symbolic_path = $assets_root_path . 'Cache';
			// if the symlink already exists remove it
			if(is_link($assets_symbolic_path)) {
				Console\Format::line('- removing ' . $cache_name , 'gray');
				@unlink($assets_symbolic_path);
				
			}
			// create the symlink
			if(@symlink($cache_assets_dir, $assets_symbolic_path)) {
				// feedback
				Console\Format::line('+ create ' . $cache_name , 'green');
			}
			else {
				// feedback
				Console\Format::line('+ creation ' . $cache_name . " /!\ FAILED" , 'red', null, ['bold']);
			}
		}
		

	}

**Comment by Jijac** [comment]
Working version even if caches do not exist 

	private static function generateSymlinksCommand() {
		// pretty introduction
		Console\Format::block('Generating assets symlinks', 'cyan', null, ['bold']);
		// define the bundles dir
		$bundles_dir = realpath(__DIR__.'/../../../../../Bundles/').'/';
		// for each bundle
		foreach(scandir($bundles_dir) as $bundle_name) {
			// bundle assets folder
			$bundles_assets_dir = $bundles_dir . $bundle_name .'/Assets/';
			// if the is no assets folder in that bundle
			if(!is_dir($bundles_assets_dir) || in_array($bundle_name,['.','..'])) {
				continue;
			} 
			Console\Format::line('Bundles/'.$bundle_name, 'white', null, ['bold']);
			// get assets for that bundle
			foreach(scandir($bundles_assets_dir) as $assets_type) {
				// the directory for theses assets in this bundle
				$bundle_assets_type_dir = $bundles_assets_dir . $assets_type . '/';
				// skip non valid directories
				if(!is_dir($bundle_assets_type_dir) || in_array($assets_type,['.','..','.DS_Store'])) {
					continue;
				}
				// set the root path
				$assets_root_path = realpath(__DIR__."/../../../../../../Public/Assets")."/{$assets_type}/";
				// if it doesn't already exist 
				if(!is_dir($assets_root_path)) {
					// create the path
					if(@mkdir($assets_root_path, 0777, true)) {
						// feedback
						Console\Format::line('  + Public/Assets/'.$assets_type.'/', 'green');
					}
					else {
						// feedback
						Console\Format::line('  X Public/Assets/'.$assets_type.'/ (failed)', 'red');
					}
				}
				// set the symlink 
				$assets_symbolic_path = $assets_root_path . $bundle_name;

				// if the symlink already exists remove it
				if(is_link($assets_symbolic_path)) {
					Console\Format::line('- removing : Public/Assets/'.$assets_type.'/'.$bundle_name.'/', 'gray');
					@unlink($assets_symbolic_path);
				
				}
				// create the symlink
				if(@symlink($bundle_assets_type_dir, $assets_root_path.$bundle_name)) {
					// feedback
					Console\Format::line('  + Public/Assets/'.$assets_type.'/'.$bundle_name.'/', 'green');
				}
				else {
					// feedback
					Console\Format::line('  X Public/Assets/'.$assets_type.'/'.$bundle_name.'/ (failed)', 'red');
				}
			}
		}
		
		// Generate Caches links
		// pretty introduction
		Console\Format::block('Generating assets caches symlinks', 'cyan', null, ['bold']);
		if(is_dir(__DIR__ . '/../../../../../Storage/Cache/Assets')){
			// define the caches dir
			$caches_dir = realpath(__DIR__ . '/../../../../../Storage/Cache/Assets').'/';
			if(is_dir($caches_dir)){
				// for each Assets cache
				foreach(scandir($caches_dir) as $cache_name) {
					// bundle assets folder
					$cache_assets_dir = $caches_dir . $cache_name .'/';
					// if the is no cache folder 
					if(!is_dir($cache_assets_dir) || in_array($cache_name,['.','..','.DS_Store'])) {
						continue;
					} 
					// set the root path
					$assets_root_path = realpath(__DIR__."/../../../../../../Public/Assets")."/{$cache_name}/";
					// set the symlink 
					$assets_symbolic_path = $assets_root_path . 'Cache';
					// if the symlink already exists remove it
					if(is_link($assets_symbolic_path)) {
						Console\Format::line('- removing ' . $cache_name , 'gray');
						@unlink($assets_symbolic_path);
				
					}
					// create the symlink
					if(@symlink($cache_assets_dir, $assets_symbolic_path)) {
						// feedback
						Console\Format::line('+ create ' . $cache_name , 'green');
					}
					else {
						// feedback
						Console\Format::line('+ creation ' . $cache_name . " /!\ FAILED" , 'red', null, ['bold']);
					}
				}
			
			}
			
		} else {
				Console\Format::line('No Assets cache where found.' , 'red');
		}
		

	}

**Comment by AnnoyingTechnology** [comment]
C'est quoi ça ?

**Comment by AnnoyingTechnology** [comment]
C'est un morceau de code fonctionnel ? si oui PR

**Comment by AnnoyingTechnology** [comment]
fixed in https://github.com/polyfony-inc/console/pull/16
